/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cinema;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        Cinema classUnderTest = new Cinema();
        assertNotNull(classUnderTest);
    }
}
